apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka
resources:
- namespace.yaml
- secret.yaml
- ../../base

images:
- name: jcy0308/pdf-module
  newTag: 93734131e947ffcb4e25c0bd9daab356e1f9f73b
