apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka
resources:
- namespace.yaml
- secret.yaml
- ../../base

images:
- name: jcy0308/pdf-module
  newTag: fd07beb55573ff43355fd7d140ce84cc0559d293
